### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/mapa-mental-lucero012#2]
[mapa mental. matematicas discretas. maribel lucero zuñiga.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-lucero012/files/7274384/mapa.mental.matematicas.discretas.maribel.lucero.zuniga.pdf)

**Comment by RichiMB** [comment]
Manejo conceptual y manejo del tema. (25 puntos)
Relación entre los conceptos.  (22 puntos)
Calidad de la presentación. (20 puntos)
Jerarquía (25 puntos)
Total de puntos: 92 puntos / 100 puntos.
Calificación: 18.4% / 20%
Calificado por: Jose Ricardo Mendez Barrios

**Comment by josealfredo79** [comment]
Bien hecho y revisado
